db:
  image: postgres
  ports:
    - "5432:5432"

api:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "5000:8000"
  volumes:
    - .:/code:rw
  links:
    - db
  environment:
    DEBUG: True
